### ISSUE TITLE
Extension daemon will not start if it is merged with system extensions

### ISSUE THREAD

**Issue by wangxa** [BigE/desk-changer#14] opened 2017-02-10 11:27 UTC
I tried to merge the desk-changer extension with the system extensions. But each time I log in, the daemon will not start, I have to manually start it.

**Comment by wangxa** [comment] 2017-02-10 11:38
By the way, the version I used is 18.

**Comment by BigE** [comment] 2017-02-10 18:03
Can you do two things for me? Check the settings for the extension and verify that "DeskChanger Autostart Daemon" is enabled as it is here. You can also check via cli by running the command `gsettings --schemadir ~/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/schemas/ get org.gnome.shell.extensions.desk-changer auto-start` which should output `true`
![screenshot from 2017-02-10 11-57-03](https://cloud.githubusercontent.com/assets/109278/22837906/3a184b02-ef88-11e6-9b68-b2a92f456bf8.png)

If this is enabled and it is still not starting automatically when you log in, you should check your gnome-shell log to see if there are any errors there caused by the extension or daemon. Thanks!

**Comment by wangxa** [comment] 2017-02-11 17:27
I install the extension in /usr/share/gnome-shell/extensions/, do you think this is the reason why the daemon will not automatically start? I can confirm I have enabled the 'DeskChanger Autostart Daemon' option.

**Comment by BigE** [comment] 2017-02-15 21:32
No, moving it to the system should not change anything. I will do some testing when I can. Its possible that the system integration does not account for that setting. Thanks for your report, I will update further when I've found something.

**Comment by wangxa** [comment] 2017-02-16 10:11
Thank you for your help.

**Closed** 2017-02-16 22:15 UTC
Labels: bug

**Comment by BigE** [comment] 2017-02-16 23:48
The change to fix this issue is waiting for review on http://extensions.gnome.org so you can grab it here or wait for the update to come through there. Thanks for finding an issue!

**Comment by wangxa** [comment] 2017-02-17 22:38
I have tried. This version fixes the problem. Thank you very much.
