### ISSUE TITLE
Gnome-shell crashes 

### ISSUE THREAD

**Issue by simonbcn** [BigE/desk-changer#48] opened 2018-04-25 14:31 UTC
```
Arch Linux
Gnome-shell 3.28.1 on Wayland
```

I've been suffering from gnome session crashes for a few weeks now and it looks like the problem is in:

> ...changing the background in gsettings/dconf from an extension is the trigger for this bug.

More info: https://bugs.archlinux.org/task/58318

**Comment by BigE** [comment] 2018-04-25 16:52
I'm going to need quite a bit more information on this. I don't currently have a setup where I can use Wayland and do not have this issue with XOrg. I'm not sure exactly what Wayland would have to do with this crash specifically?

Also, I'm having trouble seeing how this extension is related to the crash you're seeing. This extension does not change anything stylesheet related, and the only settings outside of the extension itself that it even touches are org.gnome.desktop.interface.picture-uri and org.gnome.desktop.screensaver.picture-uri. I'm not at all saying it isn't responsible... I'm just unsure where to even look to determine if there is something wrong. Hopefully if you can do a bit more digging, we'll get to the bottom of this. Thanks!

**Comment by simonbcn** [comment] 2018-04-25 16:56
Perhaps it is a Gnome bug. 
How does this extension change the wallpaper?

**Comment by BigE** [comment] 2018-04-25 16:58
It literally sets a string of the file path to the two keys shared above. Gnome internally changes the wallpaper itself based on what is set. There are no stylesheets in the extension either.

**Comment by simonbcn** [comment] 2018-04-25 17:04
It seems that is [the problem](https://bugs.archlinux.org/task/58318#comment168810): 

> I googled for this crash a bit, seems that changing the background in gsettings/dconf from an extension is the trigger for this bug.

I have disabled this extension for a few days to check if the problem is really this one. I'll talk about the results later.

**Comment by BigE** [comment] 2018-04-25 17:11
I'm starting to think this is definitely a Gnome bug. The python daemon is what actually changes the wallpaper, the extension itself does not. When I get home from work tonight I'll do some testing on my Arch laptop at home. I might be able to get Wayland going there, maybe. Can you share your current configuration of the extension? A screenshot of the extension menu should be sufficient. Thanks!

**Comment by simonbcn** [comment] 2018-04-25 17:15
![captura de pantalla de 2018-04-25 19-14-56](https://user-images.githubusercontent.com/428231/39261523-0956d99a-48bd-11e8-9ba3-4055e6429f57.png)

**Comment by BigE** [comment] 2019-10-20 06:25
Unable to reproduce and now a full rewrite is in develop. Closing. Please open a new issue if this resurfaces once a new version is released.

**Closed by BigE** 2019-10-20 06:25 UTC
Labels: help wanted
