### ISSUE TITLE
Momentary blue-background while changing backgrounds.

### ISSUE THREAD

**Issue by nickurak** [BigE/desk-changer#78] opened 2021-02-17 20:33 UTC
I'm running under wayland, if that matters.

When desk-changer switches between backgrounds, there's sometimes a momentary flash of blue in after the old background, but before the new background.

I've been trying to duplicate it -- hitting the next/previous buttons in the extension's panel menu doesn't trigger it. Maybe something about large uncached images taking longer to load sometimes? Just throwing ideas out.

**Comment by BigE** [comment] 2021-02-22 13:58
Hi @nickurak,

I've also seen this at times and I'm not sure what causes it. All this extension actually does is update the settings for the background URL in `org.gnome.desktop.background.picture-uri`. Since it is Gnome itself that actually sets the background from this URL, I suspect this is an internal issue with Gnome and not related to the extension. I'll leave this open for now until I have time to really dig in.

Thanks!

**Comment by BigE** [comment] 2021-07-31 08:01
I still haven't found anything related to the extension doing this yet. This just seems to be gnome-shell itself. I cannot reproduce it steadily, but it does happen and usually on larger resolution images. I'm closing this issue in relation to the extension itself, since we're just setting a property and gnome-shell is making the change.

**Closed by BigE** 2021-07-31 08:01 UTC

**Comment by zinkst** [comment] 2022-01-28 21:29
I may have an idea what could be the problem here. When my desktop changed to blue again I checked
```
$ gsettings get org.gnome.desktop.background picture-uri
file:///some_path/.comments/some_picture.jpg.xml
```
The contents of such a file is not a picture but some metadata generated by gthumb. 
It has .jpg in its name, and probably desk-changer will therefore use it as candiate for a background.
