### ISSUE TITLE
Tight loop causing CPU pegging

### ISSUE THREAD

**Issue by jkoelker** [BigE/desk-changer#28] opened 2017-08-04 06:59 UTC
The background randomizer while loop at [wallpaper.py#L188-L201](https://github.com/BigE/desk-changer/blob/master/desk-changer%40eric.gach.gmail.com/deskchanger/wallpapers.py#L188-L201) sometimes gets stuck where none of the conditions are satisfied and it tight loops. Locally I've inserted a `time.sleep(0.5)` to alleviate the issue at the end of the loop `if wallpaper is None`.

Since it looks like this logic is in a state of flux in other branches, I've held on refactoring the logic and submitting a PR. I believe that using a `collections.deque` object to hold the history with a `maxlen` of `x` where `x < (len(self._wallpapers) - some_const_or_precentage_of_wallpapers_len)` would ensure that at least some of the available wallpapers are always considered for placement in the queue.

If this sounds amenable I can work it out and submit a pr for further discussion.

**Comment by BigE** [comment] 2017-08-08 15:33
Thanks for finding this. I need to get my most recent changes tested and pushed through again to see if this is still happening. I'll narrow it down and fix this once I get to that point. Thank you for the submission!

**Comment by BigE** [comment] 2017-08-15 18:53
Adding several bug reports from the extension website that also correlate to this issue.

---

> Your extension, "Desk Changer" has received an error report:
> 
> What's wrong?
> daemon sometimes causes python to hit 100% cpu usage on a single core
> 
> 
> What have you tried?
> kill python, restart gnome session
> 
> 
> Automatically detected errors:
> 
> GNOME Shell Extensions did not detect any errors with this extension.
> 
> Version information:
> 
>     Shell version: 3.22.3
>     Extension version: 12

---

> Your extension, "Desk Changer" has received an error report:
> 
> on fedora 25, python process goes to 100%.  requires killing python task and restarting deskchanger daemon, or restarting gnome via alt+f2 r.

---

> Your extension, "Desk Changer" has received an error report:
> 
> What's wrong?
> Runaway python script.  After a random amount of time, the script "desk-changer-daemon.py" jumps to 100% of processing power. Sometimes it happens immediately on login, sometimes it's not  a problem for hours.
> 
> 
> 
> What have you tried?
> I kill the process.
> 
> 
> Automatically detected errors:
> 
> GNOME Shell Extensions did not detect any errors with this extension.
> 
> Version information:
> 
>     Shell version: 3.24.2
>     Extension version: 12

**Comment by BigE** [comment] 2017-08-17 21:13
I still need to do some testing myself to find out, but I'm pretty sure this will be fixed with that commit. I added a max queue length to help limit how big the history gets. I also use this length for my randomness check. Please feel free to test out the develop branch to see if the issue is resolved.

**Comment by BigE** [comment] 2017-09-12 01:09
This issue should be resolved in [version-24](https://github.com/BigE/desk-changer/releases/tag/version-24) If it occurs again, lets open a new issue since the code surrounding has changed.

**Closed by BigE** 2017-09-12 01:09 UTC
Labels: bug
