### ISSUE TITLE
Not working with Gnome 3.38

### ISSUE THREAD

**Issue by MrPestle** [BigE/desk-changer#72] opened 2020-10-23 13:26 UTC
I know Ubuntu 20.10 with Gnome 3.38 is brand new but hope this will be working asap!
Cheers

**Comment by BigE** [comment] 2020-10-23 16:14
Hi, I'm sure this is a duplicate of #71 and it should already be fixed in develop. Please open this up again with more information you're seeing a different issue. 

Thanks!

**Closed by BigE** 2020-10-23 16:14 UTC
