### ISSUE TITLE
Gio.DbusError

### ISSUE THREAD

**Issue by slash27** [BigE/desk-changer#36] opened 2018-03-30 12:38 UTC
![screenshot from 2018-03-30 18-02-58](https://user-images.githubusercontent.com/37931766/38137885-2ebb30b4-3445-11e8-9d06-198e825dc4f1.png)

Having bug error when tires to change the wallpaper and the wallpaper isn't changing by it self after the given interval.
Python is already installed and updated

**Comment by BigE** [comment] 2018-04-02 18:20
Generally when this error happens, the daemon is not running. You will have to run it from the command line manually to find out what the issue is. Just open a terminal and get into the extension directory
`cd ~/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/`
Then run the daemon itself to see what's going on. This can also be done with full debugging for more information output
`G_MESSAGES_DEBUG=all ./desk-changer-daemon.py`
If you don't see anything that stands out as an error, please paste all output here and I will take a look. Thanks!

**Comment by slash27** [comment] 2018-04-05 17:48
I am receiving this error after entering the given command.
![error](https://user-images.githubusercontent.com/37931766/38382435-978116b8-3927-11e8-9cf1-2f4e5cc1371d.png)

**Comment by BigE** [comment] 2018-04-05 18:31
Ubuntu? Hm. Can you check and make sure python-gi or python3-gi is installed? The daemon should run on python2 or python3, you will just have to make sure the respective version of python-gi is installed for it to work. Thanks!

**Comment by slash27** [comment] 2018-04-07 12:24
I checked if my pytho3-gi is installed or not and its there and updated too. What to do next?
![screenshot from 2018-04-07 17-52-03](https://user-images.githubusercontent.com/37931766/38454851-ad316948-3a8c-11e8-8f1e-07bd1cd08606.png)

**Comment by BigE** [comment] 2018-04-15 00:48
Make sure you have python-gobject installed also. This could be a case where it's automatically using python2 instead of python3.. check what version it's using by checking `python --version` in your shell.

**Comment by BigE** [comment] 2018-04-25 21:16
Any updates? I'm going to close this issue unless you've got some new information. Thanks!

**Comment by slash27** [comment] 2018-04-27 14:06
Sorry for the delay, been out of town for a while. Anyway python is already installed on my system, I've attached the screenshot for you to check.
![python](https://user-images.githubusercontent.com/37931766/39366678-3b07145a-4a52-11e8-80ab-ba0b23c6119c.png)

**Comment by sethen** [comment] 2018-08-17 18:48
@totietje That worked for me too!
@slash27 Where did you get that wall paper?  Happen to have a link?  I love it!

**Comment by sethen** [comment] 2018-08-17 18:52
I actually found it on Reddit if anyone wants it!  https://i.redd.it/wm77grlkjvf11.jpg

**Comment by rockrong** [comment] 2018-11-06 15:47
@totietje Thanks! your solution is great!

**Comment by ZahnPastor** [comment] 2019-01-31 16:08
@BigE just letting you know that this error is still there, and is easily fixable

**Comment by BigE** [comment] 2019-02-05 17:26
Hi @ZahnPastor,

Thank you for the update. Unfortunately, I haven't spent much time with maintenance of this plugin lately. I'm also currently rewriting the daemon to be written purely in JS, eliminating the need for python all together. It isn't ready yet, and won't be for a bit... so I'm leaving this issue open for reference. However, I won't be doing anything to fix the issue at this point since my focus is on the rewrite.

If anyone would like to, fix it and make a pull request. I'll happily pull it into the extension and release an update.

**Comment by BigE** [comment] 2019-10-20 06:28
Closing with the rewrite now in develop.

**Closed by BigE** 2019-10-20 06:28 UTC
